# Generated by Django 5.0 on 2023-12-10 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_candidate_created_at_candidate_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='candidate',
        ),
        migrations.RemoveField(
            model_name='note',
            name='user',
        ),
        migrations.DeleteModel(
            name='Candidate',
        ),
        migrations.DeleteModel(
            name='Note',
        ),
    ]
